### ISSUE TITLE
ssh-agent access

### ISSUE THREAD

**Issue by jdub** [buildkite-plugins/golang-buildkite-plugin#15]
We've noticed that `golang` plugin builds don't have access to ssh-agent. It's missing this lovely little snippet from the `docker` plugin:

https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command#L172

Would you like a quick PR to add this? It feels a bit hacky, though. Perhaps the `golang` plugin should be a wrapper for the `docker` plugin, so improvements flow through?

**Comment by nsuma8989** [comment]
@jdub Closing this issue. Please let us know if you are still interested in this capability and would like to contribute to it ?
